#!/bin/bash

apt update
apt upgrade -y

# Base packages
echo "Installing base packages..."
apt install -y fzf
apt install -y curl
apt install -y gcc
apt install -y git # ensure the latest git is installed to make neovim Diffview plugin work
apt install -y make build-essential procps curl libssl-dev zlib1g-dev

# Git
echo "Configuring git..."
git config --global user.name "viacheslav.tkachenko"
git config --global user.email "t.viacheslav00@gmail.com"
git config --global init.defaultBranch main
git config --global core.editor "nvim"
git config --global pull.rebase true

# Zsh
echo "Installing and configuring Zsh..."
apt install -y zsh
echo "Installing oh-my-zsh..."
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
chsh -s "$(which zsh)"
# Plugins
echo "Installing Zsh plugins..."
git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.zsh/zsh-syntax-highlighting
git clone https://github.com/agkozak/zsh-z ~/.zsh/zsh-z
# Link
rm ~/.zshrc
ln -s ~/dev/personal/dotfiles/.zshrc ~/.zshrc
zsh

# Homebrew
echo "Installing Homebrew..."
NONINTERACTIVE=1 \
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
source ~/.zshrc

# Delta (diff viewer)
echo "Installing git-delta..."
brew install git-delta
git config --global core.pager "delta"
git config --global interactive.diffFilter "delta --color-only"
git config --global delta.navigate true
git config --global delta.side-by-side true
git config --global delta.syntax-theme "Visual Studio Dark+"
git config --global delta.hunk-header-style omit
git config --global delta.dark true

## Scripts
echo "Installing custom scripts..."
ln -s ~/dev/personal/dotfiles/usr/local/bin/tmux-sessionizer /usr/local/bin/tmux-sessionizer
ln -s ~/dev/personal/dotfiles/usr/local/bin/git-pullmaster /usr/local/bin/git-pullmaster
ln -s ~/dev/personal/dotfiles/usr/local/bin/kickass /usr/local/bin/kickass
ln -s ~/dev/personal/dotfiles/usr/local/bin/git-branch-switcher /usr/local/bin/git-branch-switcher
ln -s ~/dev/personal/dotfiles/usr/local/bin/git-stash-lister /usr/local/bin/git-stash-lister
ln -s ~/dev/personal/dotfiles/usr/local/bin/git-multiproj-branch-switcher /usr/local/bin/git-multiproj-branch-switcher

chmod +x /usr/local/bin/tmux-sessionizer
chmod +x /usr/local/bin/git-pullmaster
chmod +x /usr/local/bin/kickass
chmod +x /usr/local/bin/git-branch-switcher
chmod +x /usr/local/bin/git-stash-lister
chmod +x /usr/local/bin/git-multiproj-branch-switcher

# Tmux
echo "Installing Tmux..."
apt -y install tmux
ln -s ~/dev/personal/dotfiles/.tmux.conf ~/.tmux.conf

# Node.js and npm and nvm
echo "Installing Node.js and npm using nvm..."
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
source ~/.zshrc
nvm install --lts

# Python and pyenv
echo "Installing Python and pyenv..."
curl -fsSL https://pyenv.run | bash
source ~/.zshrc
pyenv install 3.12.3
pyenv global 3.12.3
source ~/.zshrc

# Neovim
echo "Installing Neovim and dependencies..."
apt install -y ripgrep
apt install -y luarocks
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
rm -rf /opt/nvim
tar -C /opt -xzf nvim-linux-x86_64.tar.gz
ln -s ~/dev/personal/dotfiles/nvim ~/.config/nvim
