#!/usr/bin/env bash

if command -v pbcopy >/dev/null 2>&1; then
    pbcopy
elif command -v xclip >/dev/null 2>&1; then
    xclip -in -selection clipboard
elif command -v wl-copy >/dev/null 2>&1; then
    wl-copy
else
    echo "No clipboard utility found" >&2
    exit 1
fi
