#!/usr/bin/env bash

set -euo pipefail

selected=$(git stash list | fzf)

[[ -z "$selected" ]] && exit 0

stash_ref=$(echo "$selected" | sed -n 's/^\(stash@{[0-9]\+}\):.*/\1/p')

[[ -z "$stash_ref" ]] && {
  echo "Failed to extract stash reference."
  exit 1
}

git stash apply "$stash_ref"
