#!/usr/bin/env bash

set -euo pipefail

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Not inside a git repository."
  exit 1
fi

branch=$(git branch -a --sort=-committerdate | grep -v '\->' | sed 's/^..//' | fzf --prompt="Select branch: ")

[[ -z "$branch" ]] && echo "No branch selected." && exit 1

if [[ "$branch" == remotes/* ]]; then
  remote_branch="${branch#remotes/}"
  git checkout --track "$remote_branch"
else
  git checkout "$branch"
fi
