#!/bin/bash

[[ -z $TMUX ]] && exit 0

session_name=$(tmux list-sessions -F "#{session_created} #{session_name}" 2>/dev/null | sort -n | cut -d' ' -f2 | sed -n "$((${1}+1))p")
if [[ -n $session_name ]]; then
    tmux switch-client -t "$session_name" 2>/dev/null
else
    echo "Session at index $1 not found" >&2
fi
