#!/usr/bin/env bash

set -euo pipefail

# Usage
# k get cm my-cm -n my-ns -o jsonpath='{.data}' | to-env

FROM_HOST_REGEX="${FROM_HOST_REGEX:-.*\.svc\.cluster\.local}"
TO_HOST="${TO_HOST:-host.docker.internal}"
FROM_PROTOCOL="${FROM_PROTOCOL:-http}"
TO_PROTOCOL="${TO_PROTOCOL:-http}"

jq \
| yq -P \
| sed 's/: /=/' \
| sed -E "s|${FROM_PROTOCOL}://(${FROM_HOST_REGEX})|${TO_PROTOCOL}://${TO_HOST}|g"
